import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SAMPLE_MASTERS = [
  {
    partCode: 'SP-LS-001',
    productName: '본드',
    spec: '32X2',
    unit: 'EA',
    optimalQty: 10,
    manufacturer: '삼성',
    storageLocation: '사출본동',
    leadTimeDays: 7,
    sortOrder: 1,
    isActive: true,
  },
  {
    partCode: 'SP-LS-002',
    productName: '히터카트리지',
    spec: 'Ø6.5×80',
    unit: 'EA',
    optimalQty: 5,
    manufacturer: '코리아히터',
    storageLocation: '사출본동',
    leadTimeDays: 14,
    sortOrder: 2,
    isActive: true,
  },
  {
    partCode: 'SP-LS-003',
    productName: '노즐팁',
    spec: 'M6-0.5',
    unit: 'EA',
    optimalQty: 20,
    manufacturer: '하스코',
    storageLocation: '사출본동',
    leadTimeDays: 10,
    sortOrder: 3,
    isActive: true,
  },
  {
    partCode: 'SP-LS-004',
    productName: '유압유',
    spec: 'ISO-46',
    unit: 'L',
    optimalQty: 4,
    manufacturer: 'SK',
    storageLocation: '자재창고',
    leadTimeDays: 5,
    sortOrder: 4,
    isActive: true,
  },
  {
    partCode: 'SP-LS-005',
    productName: '그리스',
    spec: 'NLGI-2',
    unit: 'EA',
    optimalQty: 8,
    manufacturer: '쉘',
    storageLocation: '자재창고',
    leadTimeDays: 5,
    sortOrder: 5,
    isActive: true,
  },
  {
    partCode: 'SP-LS-006',
    productName: '필터카트리지',
    spec: '10μm',
    unit: 'EA',
    optimalQty: 6,
    manufacturer: '마닉',
    storageLocation: '사출본동',
    leadTimeDays: 12,
    sortOrder: 6,
    isActive: true,
  },
  {
    partCode: 'SP-LS-007',
    productName: 'O링',
    spec: 'P-20',
    unit: 'EA',
    optimalQty: 30,
    manufacturer: 'NOK',
    storageLocation: '사출본동',
    leadTimeDays: 7,
    sortOrder: 7,
    isActive: true,
  },
  {
    partCode: 'SP-LS-008',
    productName: '서보밸브',
    spec: 'SV-100',
    unit: 'EA',
    optimalQty: 2,
    manufacturer: '유진',
    storageLocation: '전기실',
    leadTimeDays: 21,
    sortOrder: 8,
    isActive: true,
  },
  {
    partCode: 'SP-LS-009',
    productName: '온도센서',
    spec: 'K-Type',
    unit: 'EA',
    optimalQty: 4,
    manufacturer: '오메가',
    storageLocation: '전기실',
    leadTimeDays: 14,
    sortOrder: 9,
    isActive: true,
  },
  {
    partCode: 'SP-LS-010',
    productName: '냉각호스',
    spec: 'Ø8×2M',
    unit: 'EA',
    optimalQty: 6,
    manufacturer: '동양',
    storageLocation: '사출본동',
    leadTimeDays: 7,
    sortOrder: 10,
    isActive: true,
  },
  {
    partCode: 'SP-LS-011',
    productName: '사출스크류',
    spec: 'Ø35×1200',
    unit: 'EA',
    optimalQty: 1,
    manufacturer: '하스코',
    storageLocation: '금형동',
    leadTimeDays: 30,
    sortOrder: 11,
    isActive: true,
  },
  {
    partCode: 'SP-LS-012',
    productName: '체크밸브',
    spec: 'CV-25',
    unit: 'EA',
    optimalQty: 3,
    manufacturer: '파카',
    storageLocation: '사출본동',
    leadTimeDays: 14,
    sortOrder: 12,
    isActive: true,
  },
  {
    partCode: 'SP-LS-013',
    productName: '에어필터',
    spec: 'AF-200',
    unit: 'EA',
    optimalQty: 10,
    manufacturer: 'SMC',
    storageLocation: '자재창고',
    leadTimeDays: 7,
    sortOrder: 13,
    isActive: true,
  },
  {
    partCode: 'SP-LS-014',
    productName: '솔레노이드밸브',
    spec: 'SV-220',
    unit: 'EA',
    optimalQty: 4,
    manufacturer: 'SMC',
    storageLocation: '전기실',
    leadTimeDays: 10,
    sortOrder: 14,
    isActive: true,
  },
  {
    partCode: 'SP-LS-015',
    productName: '윤활유펌프',
    spec: 'LP-1',
    unit: 'EA',
    optimalQty: 2,
    manufacturer: '비쇼프',
    storageLocation: '사출본동',
    leadTimeDays: 21,
    sortOrder: 15,
    isActive: true,
  },
  {
    partCode: 'SP-LS-016',
    productName: '플라스틱호퍼',
    spec: '50L',
    unit: 'EA',
    optimalQty: 2,
    manufacturer: '자체',
    storageLocation: '사출본동',
    leadTimeDays: 14,
    sortOrder: 16,
    isActive: true,
  },
  {
    partCode: 'SP-LS-017',
    productName: '건조기필터',
    spec: 'DF-10',
    unit: 'EA',
    optimalQty: 4,
    manufacturer: '마닉',
    storageLocation: '사출본동',
    leadTimeDays: 10,
    sortOrder: 17,
    isActive: true,
  },
  {
    partCode: 'SP-LS-018',
    productName: '로드셀',
    spec: '500kg',
    unit: 'EA',
    optimalQty: 2,
    manufacturer: 'CAS',
    storageLocation: '전기실',
    leadTimeDays: 21,
    sortOrder: 18,
    isActive: true,
  },
  {
    partCode: 'SP-LS-019',
    productName: '커넥터플러그',
    spec: '16P',
    unit: 'EA',
    optimalQty: 15,
    manufacturer: '하이닉스',
    storageLocation: '전기실',
    leadTimeDays: 7,
    sortOrder: 19,
    isActive: false,
    remarks: '단종 예정',
  },
  {
    partCode: 'SP-LS-020',
    productName: '냉각팬',
    spec: '120×120',
    unit: 'EA',
    optimalQty: 6,
    manufacturer: 'EBM',
    storageLocation: '자재창고',
    leadTimeDays: 10,
    sortOrder: 20,
    isActive: true,
  },
] as const;

async function main() {
  for (const row of SAMPLE_MASTERS) {
    await prisma.sparePartMaster.upsert({
      where: { partCode: row.partCode },
      create: {
        partCode: row.partCode,
        machineBrand: '',
        productName: row.productName,
        spec: row.spec,
        unit: row.unit,
        optimalQty: row.optimalQty,
        manufacturer: row.manufacturer,
        storageLocation: row.storageLocation,
        leadTimeDays: row.leadTimeDays,
        remarks: 'remarks' in row ? row.remarks : null,
        isActive: row.isActive,
        sortOrder: row.sortOrder,
        createdBy: 'seed',
        updatedBy: 'seed',
      },
      update: {
        productName: row.productName,
        spec: row.spec,
        unit: row.unit,
        optimalQty: row.optimalQty,
        manufacturer: row.manufacturer,
        storageLocation: row.storageLocation,
        leadTimeDays: row.leadTimeDays,
        remarks: 'remarks' in row ? row.remarks : null,
        isActive: row.isActive,
        sortOrder: row.sortOrder,
        updatedBy: 'seed',
      },
    });
  }
  console.log(`Seeded ${SAMPLE_MASTERS.length} spare part masters.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
