-- AlterTable
ALTER TABLE "MailMenu" ADD COLUMN "menuQuery" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MailMenu" ADD COLUMN "recipientEmails" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "MailMenu" ADD COLUMN "sendDaysMask" INTEGER NOT NULL DEFAULT 127;
ALTER TABLE "MailMenu" ADD COLUMN "sendTimes" JSONB NOT NULL DEFAULT '[]';
